<template>
  <div>
    <b-col>
      <div
        class="
          d-flex
          flex-column
          min-vh-100
          container
          justify-content-center
          align-items-center
          col-sm-12 col-md-6
        "
      >
        <img class="d-block mx-auto" src="../../assets/logo.png" alt="Vue" />
        <div class="d-flex flex-column mx-auto">
          <h2 class="d-flex justify-content-center text-center mt-3">
            Welcome to your Laravel Validation app!
          </h2>
          <div
            class="
              d-flex
              flex-column
              justify-content-center
              align-items-center
              mx-auto
              px-5
            "
          >
            <b-row>
              <p class="text-center">
                This is vue/laravel app generated by the
                <a href="https://flatlogic.com/generator"
                  ><span>Flatlogic Web App Generator</span></a
                >
                For guides and documentation please check your local README.md
                and
                <a href="https://flatlogic.com/documentation"
                  ><span>Flatlogic documentation</span></a
                >
              </p>
            </b-row>
          </div>
          <div class="d-flex justify-content-center">
            <router-link to="/login" class="text-decoration-none">
              <b-button
                class="
                  d-block
                  btn-default
                  p-2
                  px-5
                  fs-lg
                  text-center
                  mb-3
                  mt-1
                  mx-3
                "
                >LOGIN</b-button
              >
            </router-link>
            <router-link to="/register" class="text-decoration-none">
              <b-button
                class="
                  d-block
                  btn-default
                  p-2
                  px-5
                  fs-lg
                  text-center
                  mb-3
                  mt-1
                  mx-3
                "
                >SIGN UP</b-button
              >
            </router-link>
          </div>

          <div
            class="
              d-flex
              flex-column
              justify-content-center
              align-items-center
              text-center
              mx-auto
              px-5
              mt-3
            "
          >
            <b-row>
              <b-col>
                <a target="_blank" href="https://vuejs.org/"
                  ><span> Vue.js </span></a
                >
              </b-col>
              <b-col>
                <a target="_blank" href="https://laravel.com/"
                  ><span> Laravel </span></a
                >
              </b-col>
              <b-col>
                <a target="_blank" href="https://flatlogic.com/forum"
                  ><span> Flatlogic Forum </span></a
                >
              </b-col>
              <b-col>
                <a target="_blank" href="https://bootstrap-vue.org/"
                  ><span> BootstrapVue </span></a
                >
              </b-col>
            </b-row>
          </div>
        </div>
      </div>
    </b-col>
  </div>
</template>

<script>
  export default {
    name: 'starterPage',
  };
</script>
